### ISSUE TITLE
fix up CO2 documentation

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/Climate#12]
@forestgeoadm  ,

@biancaglez loaded CO2 data + script and put a readme here: https://github.com/forestgeo/Climate/tree/master/Other_environmental_data. It's ready for your review.

@biancaglez , one small comment-- it would be helpful to mention the time periods covered by each record.

**Comment by biancaglez** [comment]
@teixeirak 
done -- thanks!

**Comment by forestgeoadm** [comment]
@teixeirak, great, thanks for letting me know!  @biancaglez, it's on my list to read through this soon - if not today, early next week.

**Comment by teixeirak** [comment]
I did a bit of rearranging/ fix-up to the readme (e.g., clarified presentation a bit, hyperlinks rather than full url). One thing we still probably want to add is how to cite (this info should be in original readmes, but helpful if we can be clear on that info in our readme. (Caly is working on this issue for the repo as a whole, so let's be consistent.)

**Comment by maurolepore** [comment]
It's so nice to see you all working together! Big shout to Caly for engaging with Krista's lab.

**Comment by forestgeoadm** [comment]
Thanks, @maurolepore - @teixeirak has been a very patient teacher!

**Comment by biancaglez** [comment]
Do we need to close this issue as well @teixeirak ?

**Comment by teixeirak** [comment]
Yes; I think this is all good. Thanks!
