### ISSUE TITLE
.RProj, etc.

### ISSUE THREAD

**Issue by forestgeoadm** [forestgeo/Climate#15]
Hi @biancaglez, 

I'm taking a look at the folder/file structure of the Climate Data Portal and was wondering if you could help me to understand what the .RProj.user folder is and the .Rhistory and Climate.Rproj files are/if they're connected.  

Take care,
Caly

**Comment by biancaglez** [comment]
hi @forestgeoadm -- can you link that here so I know we are talking about the same thing? Do you mean the CRU data?

**Comment by teixeirak** [comment]
https://github.com/forestgeo/Climate/tree/master/.Rproj.user

**Comment by biancaglez** [comment]
Thanks, Krista. I think that can be deleted. @forestgeoadm

**Comment by forestgeoadm** [comment]
Thank you, both!

**Comment by teixeirak** [comment]
My attempt to delete actually didn't work.... No idea why.

**Comment by biancaglez** [comment]
Want me to try? Were there any errors? The scripts we wrote shouldn't depend on this project.

**Comment by teixeirak** [comment]
Sure. It seems I can delete individual files, but not the whole thing. Nothing shows up in my file viewer (on Mac), but its still there in the online version.

**Comment by biancaglez** [comment]
Doneso https://github.com/forestgeo/Climate 

@teixeirak I think this can be closed now

**Comment by teixeirak** [comment]
Okay, thanks. That did create a couple other files, though-- .Rhistory and a scripts file (old path)

**Comment by biancaglez** [comment]
Okay should be all fixed up https://github.com/forestgeo/Climate

If it isn't @teixeirak pls reopen issue.
