### ISSUE TITLE
fix (lots of) broken URLs

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/Climate#20]
@forestgeoadm , @biancaglez , I've been revamping the organizational structure of this repo, and as a result breaking lots of URLs in the readme files, [this file](https://github.com/forestgeo/Climate/blob/master/Data_Products_Summary/ForestGEO%20climate%20data%20sources.csv), and scripts. I'm still working on the reorganization, so please hold off on fixing them just yet, but I want you to be aware.

**Comment by forestgeoadm** [comment]
Sounds good - thanks for letting me know!

**Comment by teixeirak** [comment]
I think we have final folder names/ organization. 

@forestgeoadm , you can go ahead and update URLs throughout.

**Comment by biancaglez** [comment]
FYI I've fixed links on my end :D

**Comment by forestgeoadm** [comment]
Thanks for the status updated, @biancaglez. I'm fixing links as I go/ad hoc adding data use/attribution text.

**Comment by teixeirak** [comment]
There are also lots of broken links in [This file](https://github.com/forestgeo/Climate/blob/master/Directory/ForestGEO%20climate%20data%20sources.csv).

**Comment by forestgeoadm** [comment]
Really?  I copy-and-pasted a number of URLs from the spreadsheet, but they worked for me.

If you can direct more towards the broken links I'm happy to help update them.  I'll need a quick lesson in how to edit a file like that, though, as I've only edited READMEs thus far and the edit tab makes the whole table look like a jumble of columns

**Comment by teixeirak** [comment]
There are quite a few in the field `Data.URL.or.location`. If you filter by "github" they'll come up. There are some (PRISM) in a private repo, but the rest are in this repo.

**Comment by forestgeoadm** [comment]
Hi @teixeirak, ah, yes - now I see what you're talking about.  I downloaded the file as a CSV.  If I make the edits in Excel, can I simply upload the updated version (rather than trying to work with the text file sans columns in the edit view of GitHub)?

**Comment by teixeirak** [comment]
Yes, you could edit and push via GitHub desktop, or I'm sure there's a way to do a pull request with the single file (although I'm not familiar with that since I always go through desktop). If its complicated, you could always send to me, and I could push.

**Comment by forestgeoadm** [comment]
Sounds like a plan - thanks for thinking through these possibilities with me.

**Comment by forestgeoadm** [comment]
Hmmm....I edited URLs to update new GitHub links (I ignored https://github.com/forestgeo/Climate/  and https://github.com/forestgeo/Climate/private, as they were PRSIM links, like you indicated).  Then I saved the file as a text file, copy-and-pasted to edit the Directory in GitHub and was met with this screen:

![image](https://user-images.githubusercontent.com/26120326/88577050-632c6a80-d014-11ea-9ada-e44f74982058.png)

I seem to have made a mistake, though I'm not sure what it is - I'm sorry!  

[ForestGEO climate data sources_07.27.20.txt](https://github.com/forestgeo/Climate/files/4983819/ForestGEO.climate.data.sources_07.27.20.txt)

**Comment by teixeirak** [comment]
Could you please send me the .csv file?  I'll load via GitHub Desktop

**Comment by forestgeoadm** [comment]
Sent!

**Comment by teixeirak** [comment]
Okay, just pushed it. Thanks!

**Comment by teixeirak** [comment]
This seems to be resolved.
