### ISSUE TITLE
making .csv files easily accessible 

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/Climate#21]
@forestgeoadm , you asked about downloading single .csv files...  Let's use [`ForestGEO climate data sources.csv`](https://github.com/forestgeo/Climate/blob/master/Data_Products_Summary/ForestGEO%20climate%20data%20sources.csv) as an example. The way to do this would be go to `Raw` and then copy-paste into Excel or such, then convert text to columns using comma delimiter. 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/6355854/86291988-ebf2ea80-bbbd-11ea-8b0b-3bc13cf34642.png">

For this particular file (and probably others), that doesn't work nicely. Thus, it  isn't a great solution, but seems to be the best there is. (I consulted @rudeboybert on this.)

For files that we want to be super user friendly, like `ForestGEO climate data sources.csv`, I need to think of some other solution--or at least convert them to formats that would be cleaner with the copy-paste.

**Comment by rudeboybert** [comment]
(Sorry @teixeirak, I neglected your ask of the final step of actually having a .csv file)

You could do the following after opening the "raw" version of the page. In your browser's menu bar, go to File -> Save Page As... At that point on my browser at least (macOS using Chrome as a browser) I have the option of saving as a CSV. If you don't have that option, making sure to save the page with filename that ends in .csv might do the trick.

**Comment by rudeboybert** [comment]
This on my end at least saves me the trouble of cutting and pasting into another program. Please let me know if this doesn't work for you.

**Comment by forestgeoadm** [comment]
Hi @rudeboybert and @teixeirak, 

Thank you for these instructions - they were super novice friendly!  Working on PC and in Chrome I opened the raw version, did "Ctrl" + "S," and saved the CSV option (which came up as the default option).

Take care,
Caly

**Comment by forestgeoadm** [comment]
Hi @rudeboybert & @teixeirak,

I added a  "Quick Tip" blurb to the [main README page](https://github.com/forestgeo/Climate/blob/master/README.md#about-this-repository) with these instructions.  Hopefully that helps orient folks who are new to GitHub.

Take care,
Caly

**Comment by teixeirak** [comment]
Thanks, Caly!

**Comment by forestgeoadm** [comment]
My pleasure!
