### ISSUE TITLE
Novice question about creating README files

### ISSUE THREAD

**Issue by forestgeoadm** [forestgeo/Climate#25]
Hi @teixeirak and @biancaglez 

I know how to edit README files in GitHub, but am I able to create one in GitHub, or do I need to create a .MD file somewhere else (in which case...I don't know how to do that)?  This is a general question, but most immediately I thought I could create a README (at least in a skeletal form) for [SCBI's SPEI data](https://github.com/forestgeo/Climate/tree/master/Climate_Data/SPEI/SCBI)

Take care,
Caly

**Comment by teixeirak** [comment]
Hi Caly,

Here are a couple screenshots showing how to do this: 
![image](https://user-images.githubusercontent.com/6355854/86952474-0cbcc200-c121-11ea-9376-82e71170bb32.png)

In this example, this would create a new file (Readme.md) *in a new folder* ("example"): 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/6355854/86952441-00386980-c121-11ea-98fb-62f5f29e45e7.png">

**Comment by forestgeoadm** [comment]
Wonderful - thank you!
