### ISSUE TITLE
2019 Met-tower data unusable

### ISSUE THREAD

**Issue by camerondow35** [forestgeo/Climate#33]
[https://github.com/forestgeo/Climate/blob/master/Climate_Data/Met_Stations/SCBI/ForestGEO_met_station-SCBI/Data/SCB_Metdata_5min_2019.csv](url) 

The 2019 csv has all of the data entered into a single row so it is unusable. Is there a quick fix to this?

**Comment by teixeirak** [comment]
Hmmm.... The file I see looks fine. Here it is after comma delimination in Excel:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/6355854/89719669-b8636700-d998-11ea-8084-6c19944327ed.png">

**Comment by camerondow35** [comment]
Strange! Here's what it looks like for me: 
![image](https://user-images.githubusercontent.com/55721987/89719957-9a4b3600-d99b-11ea-8c4f-194a1c3acd4a.png)

I've tried re-cloning the repo and it's still the same. All of the other files are fine.

**Comment by teixeirak** [comment]
Try now. 
For the record, here's how to fix that in Excel:
![image](https://user-images.githubusercontent.com/6355854/89720447-59a1eb80-d9a0-11ea-8620-67b1e3259528.png)
![image](https://user-images.githubusercontent.com/6355854/89720449-61619000-d9a0-11ea-998b-537f2824de1b.png)

**Comment by camerondow35** [comment]
Oh, cool - Never seen that before but it worked. Thanks!
