### ISSUE TITLE
readme for so2 and nox data

### ISSUE THREAD

**Issue by biancaglez** [forestgeo/Climate#38]
@forestgeoadm the SO2 and NOx data is ready and available here: 
https://github.com/forestgeo/Climate/tree/master/Other_environmental_data/so2_nox_data

Here are the notes you need for a readme for this new data. Let me know if you have any questions and happy to provide answers :D 

Bianca 

------

resources for readme:

wiki instructions on running gridding https://github.com/JGCRI/CEDS/wiki/User_Guide#use-instructions
download the gridding proxies here https://zenodo.org/record/3606753#.X1kTUmdTk6U
CEDS data citation:
Hoesly, Rachel M., O'Rourke, Patrick R, Smith, Steven J., Feng, Leyang, Klimont, Zbigniew, Janssens-Maenhout, Greet, … Muwan, Presley. (2020). CEDS v_2019_12_23 Emission Data (Version v_2019_12_23) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3606753

Special thanks to https://github.com/ssmithClimate for guidance in editing and using the G1.1.grid_bulk_emissions.R script

Steps:

Downloaded the following files from Zenodo, unzipped, select relevant files) and stored in "C:/Users/GonzalezB2/Desktop/Smithsonian/CEDS/final-emissions/"
_______ CEDS_NOx_emissions_by_country_CEDS_sector_v_2019_12_23.csv
_______ CEDS_SO2_emissions_by_country_CEDS_sector_v_2019_12_23.csv

Edited and debugged G1 script to generate NC files from these. Stored these files in the intermediate output of CEDS directory
Edits and bugs found in G1 scipt here:
Change relevent atmospheric metric : line 39 in module G script to
if ( is.na( em ) ) em <- "NOx" # change to nox or s02

module G bug identified (CEDS team is now fixing)
addd , meta = FALSE ) to all readData() functions

Write script below using these files to grab data at forestgeo sites
https://github.com/forestgeo/Climate/blob/master/Other_environmental_data/so2_nox_data/forest_geo_nos_so2.R

**Comment by teixeirak** [comment]
Thanks so much, @biancaglez !

**Comment by forestgeoadm** [comment]
Hi @biancaglez, thank you for compiling these resources.  I'm sorry that I didn't respond to them on Friday.  I'm in the thick of a few time sensitive projects, but I wanted to acknowledge your message and will start on the READMEs as soon as I'm able.

**Comment by forestgeoadm** [comment]
Hi @biancaglez, I've just put together a first draft of the SO2 & NOx readme.  I pulled from your info above and modelled it on the CO2 README.  There are a few files in the folder that I didn't link to b/c I wasn't sure what they do.  Please edit as desired!

**Comment by biancaglez** [comment]
This is great! 

If you can, I would include the following steps (they are in chronological order) & I think it would be clearer. Right now it seems as if it's just my script that generates the data - when really there are several steps just to get data to the script..... 

Thanks :) - B

> Steps:
> 
> Download the following files from Zenodo, unzip, select relevant files) and stored in "C:/Users/GonzalezB2/Desktop/Smithsonian/CEDS/final-emissions/"
> _______ CEDS_NOx_emissions_by_country_CEDS_sector_v_2019_12_23.csv
> _______ CEDS_SO2_emissions_by_country_CEDS_sector_v_2019_12_23.csv
> 
> Edited and debugged Module G.G1 script to generate NC files from these. Stored these files in the intermediate output of CEDS directory
> Edits and bugs found in G1 scipt here:
> Change relevent atmospheric metric : line 39 in module G script to
> if ( is.na( em ) ) em <- "NOx" # change to nox or s02
> 
> module G bug identified (CEDS team is now fixing)
> addd , meta = FALSE ) to all readData() functions
> 
> Write script below using these files to grab data at forestgeo sites
> https://github.com/forestgeo/Climate/blob/master/Other_environmental_data/so2_nox_data/forest_geo_nos_so2.R

**Comment by teixeirak** [comment]
Thanks @biancaglez  and @forestgeoadm ! It would be great to add a little more context about the original source. Note that its emissions (as opposed to deposition),spatial resolution, etc. Thanks!

**Comment by forestgeoadm** [comment]
Hi @biancaglez, ah, okay...so, in order for anyone to run the script themselves, they would first need to access data that it refers to, and the above instructions allow them to do that?  If that's the case, I'll put everything into present tense, add numbers before each step, and make it a clearer "how-to" directive in the script section.

**Comment by biancaglez** [comment]
https://github.com/forestgeo/Climate/blob/master/Other_environmental_data/so2_nox_data/G1.1.grid_bulk_emissions.R

^^  is the script we have to run before we run mine (including the bug edits above). You can also link to it from the CEDS repo found here: https://github.com/JGCRI/CEDS/blob/master/code/module-G/G1.1.grid_bulk_emissions.R

**Comment by biancaglez** [comment]
these are also great resources to include: 

wiki instructions on running gridding https://github.com/JGCRI/CEDS/wiki/User_Guide#use-instructions
download the gridding proxies here https://zenodo.org/record/3606753#.X1kTUmdTk6U

**Comment by forestgeoadm** [comment]
Hi, @biancaglez and @teixeirak!  I've done my best to integrate the above steps and resources.  I tweaked a few words for formatting and consistency - would you please check to ensure that I didn't inadvertently misrepresent any instructions?

I've also changed the header to indicate that the data is emissions data, and I pulled (verbatim - is that in poor taste/is there a non-awkward way to indicate that I pulled language from the CEDS repo?) language to contextualize CEDS data - please feel free to modify or point me in the direction of better/different content.

**Comment by teixeirak** [comment]
Looks great from my end; thanks!

**Comment by biancaglez** [comment]
also looks great on my end
